### ISSUE TITLE
Task List for Milestone 4

### ISSUE THREAD

**Issue by naclsodium** [ubco-W2022T2-data301/project-group-group12#4]
- [x] Task 1: Setting up pipeline- wrangle, modify data and add it to the processed data folder
- [x] Build and Test method chains for wrangling data
- [x] Represent your findings visually - including titles, axis labels, etc. and make comments in markdown code to explain what you are doing
