### ISSUE TITLE
Milestone 6 Task List and A+ Requirements

### ISSUE THREAD

**Issue by haiderbm** [ubco-W2022T2-data301/project-group-group12#9]
- [x] Address Project Feedback
- [x] Create a single markdown file. This is our final report!
- [x] Make the repository public
- [x] Create a release for the repository

For A+, ensure there are:

- [x] Multiple datasets
- [x] Sophisticated Tableau dashboard
- [x] Deep analysis and insightful commentary
- [x] Effective use of GitHub issues
- [x] Use of functions in wrangling, processing and cleaning
- [x] Complex method chaining
- [x] Effective use of git branches and pull requests
- [x] 4+ student hours
- [x] Extra "flair" and effort
